version: '3.7'
services:
  backend:
    container_name: backend
    build: ./backend
    working_dir: /backend/
    volumes:
      - ./backend/:/backend 
    env_file: ./.env
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    depends_on:
     - db

  frontend:
    image: node:15.13-alpine
    env_file:
      - ./.env
    command: sh entrypoint.sh
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend

  nginx:
    restart: on-failure
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend

  db:
    image: postgres:12.0-alpine
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: