# Generated by Django 4.1 on 2022-08-31 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protein',
            options={'ordering': ['-pk']},
        ),
    ]
