# Generated by Django 4.1 on 2022-09-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_alter_protein_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='cellular_processes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_functions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='reactome_pathways',
            field=models.TextField(),
        ),
    ]
